hm. that was not a good patch.
>>> g = pygeoip.GeoIP("GeoLiteCity.dat",pygeoip.MMAP_CACHE)
pygeoip/__init__.py:135: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if (PY3 and delim == chr(255) * 3) or (not PY3 and delim == unicode(chr(255) * 3, "unicode_escape")):
>>> g.record_by_addr("24.24.24.24")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pygeoip/__init__.py", line 557, in record_by_addr
    raise GeoIPError('Invalid database type; record_* methods expect City database')
pygeoip.GeoIPError: Invalid database type; record_* methods expect City database